// Seed list: [shortName, domain, region, type, nameEn, nameUz, nameRu].
// Everyone starts at 0 POWER — the board is never pre-filled with invented
// numbers. Admins add, rename and hide entries from /admin/universities.
type Row = [string, string, string, "STATE" | "PRIVATE" | "INTERNATIONAL", string, string, string]

export const UNIVERSITIES: Row[] = [
  ["NUUz", "nuu.uz", "TASHKENT_CITY", "STATE", "National University of Uzbekistan", "Oʻzbekiston Milliy universiteti", "Национальный университет Узбекистана"],
  ["TUIT", "tuit.uz", "TASHKENT_CITY", "STATE", "Tashkent University of Information Technologies", "Toshkent axborot texnologiyalari universiteti", "Ташкентский университет информационных технологий"],
  ["TSUE", "tsue.uz", "TASHKENT_CITY", "STATE", "Tashkent State University of Economics", "Toshkent davlat iqtisodiyot universiteti", "Ташкентский государственный экономический университет"],
  ["UWED", "uwed.uz", "TASHKENT_CITY", "STATE", "University of World Economy and Diplomacy", "Jahon iqtisodiyoti va diplomatiya universiteti", "Университет мировой экономики и дипломатии"],
  ["WIUT", "wiut.uz", "TASHKENT_CITY", "INTERNATIONAL", "Westminster International University in Tashkent", "Toshkent xalqaro Vestminster universiteti", "Международный Вестминстерский университет в Ташкенте"],
  ["INHA", "inha.uz", "TASHKENT_CITY", "INTERNATIONAL", "Inha University in Tashkent", "Toshkent shahridagi Inha universiteti", "Университет Инха в Ташкенте"],
  ["TTPU", "polito.uz", "TASHKENT_CITY", "INTERNATIONAL", "Turin Polytechnic University in Tashkent", "Toshkent shahridagi Turin politexnika universiteti", "Туринский политехнический университет в Ташкенте"],
  ["MDIST", "mdis.uz", "TASHKENT_CITY", "INTERNATIONAL", "Management Development Institute of Singapore in Tashkent", "Toshkent shahridagi Singapur menejmentni rivojlantirish instituti", "Сингапурский институт развития менеджмента в Ташкенте"],
  ["TSTU", "tdtu.uz", "TASHKENT_CITY", "STATE", "Tashkent State Technical University", "Toshkent davlat texnika universiteti", "Ташкентский государственный технический университет"],
  ["TSUL", "tsul.uz", "TASHKENT_CITY", "STATE", "Tashkent State University of Law", "Toshkent davlat yuridik universiteti", "Ташкентский государственный юридический университет"],
  ["TMA", "tma.uz", "TASHKENT_CITY", "STATE", "Tashkent Medical Academy", "Toshkent tibbiyot akademiyasi", "Ташкентская медицинская академия"],
  ["TIIAME", "tiiame.uz", "TASHKENT_CITY", "STATE", "TIIAME National Research University", "TIQXMMI Milliy tadqiqot universiteti", "Национальный исследовательский университет ТИИИМСХ"],
  ["TSPU", "tdpu.uz", "TASHKENT_CITY", "STATE", "Tashkent State Pedagogical University", "Toshkent davlat pedagogika universiteti", "Ташкентский государственный педагогический университет"],
  ["UzSWLU", "uzswlu.uz", "TASHKENT_CITY", "STATE", "Uzbekistan State World Languages University", "Oʻzbekiston davlat jahon tillari universiteti", "Узбекский государственный университет мировых языков"],
  ["TSUOS", "tsuos.uz", "TASHKENT_CITY", "STATE", "Tashkent State University of Oriental Studies", "Toshkent davlat sharqshunoslik universiteti", "Ташкентский государственный университет востоковедения"],
  ["TAQI", "taqi.uz", "TASHKENT_CITY", "STATE", "Tashkent University of Architecture and Civil Engineering", "Toshkent arxitektura-qurilish universiteti", "Ташкентский архитектурно-строительный университет"],
  ["TKTI", "tkti.uz", "TASHKENT_CITY", "STATE", "Tashkent Institute of Chemical Technology", "Toshkent kimyo-texnologiya instituti", "Ташкентский химико-технологический институт"],
  ["TSTrU", "tstu.uz", "TASHKENT_CITY", "STATE", "Tashkent State Transport University", "Toshkent davlat transport universiteti", "Ташкентский государственный транспортный университет"],
  ["TSAU", "tdau.uz", "TASHKENT_REGION", "STATE", "Tashkent State Agrarian University", "Toshkent davlat agrar universiteti", "Ташкентский государственный аграрный университет"],
  ["NewUU", "newuu.uz", "TASHKENT_CITY", "STATE", "New Uzbekistan University", "Yangi Oʻzbekiston universiteti", "Университет Новый Узбекистан"],
  ["Webster", "webster.uz", "TASHKENT_CITY", "INTERNATIONAL", "Webster University in Tashkent", "Toshkent shahridagi Vebster universiteti", "Университет Вебстера в Ташкенте"],
  ["Amity", "amity.uz", "TASHKENT_CITY", "INTERNATIONAL", "Amity University Tashkent", "Toshkent shahridagi Amiti universiteti", "Университет Амити в Ташкенте"],
  ["AUT", "ajou.uz", "TASHKENT_CITY", "INTERNATIONAL", "Ajou University in Tashkent", "Toshkent shahridagi Ajou universiteti", "Университет Аджу в Ташкенте"],
  ["MSU", "msu.uz", "TASHKENT_CITY", "INTERNATIONAL", "Lomonosov Moscow State University, Tashkent branch", "M. V. Lomonosov nomidagi MDU Toshkent filiali", "Филиал МГУ имени М. В. Ломоносова в Ташкенте"],
  ["CAU", "centralasian.uz", "TASHKENT_CITY", "PRIVATE", "Central Asian University", "Central Asian University", "Central Asian University"],
  ["KIUT", "kiut.uz", "TASHKENT_CITY", "PRIVATE", "Kimyo International University in Tashkent", "Toshkent Kimyo xalqaro universiteti", "Международный университет Кимё в Ташкенте"],
  ["TEAM", "teamuni.uz", "TASHKENT_CITY", "PRIVATE", "TEAM University", "TEAM universiteti", "Университет TEAM"],
  ["MU", "millatumidi.uz", "TASHKENT_CITY", "PRIVATE", "Millat Umidi University", "Millat Umidi universiteti", "Университет Миллат Умиди"],
  ["JDU", "jdu.uz", "TASHKENT_CITY", "PRIVATE", "Japan Digital University", "Yaponiya raqamli universiteti", "Японский цифровой университет"],
  ["SamSU", "samdu.uz", "SAMARKAND", "STATE", "Samarkand State University", "Samarqand davlat universiteti", "Самаркандский государственный университет"],
  ["SamSMU", "sammu.uz", "SAMARKAND", "STATE", "Samarkand State Medical University", "Samarqand davlat tibbiyot universiteti", "Самаркандский государственный медицинский университет"],
  ["Silk Road", "univ-silkroad.uz", "SAMARKAND", "STATE", "Silk Road International University of Tourism and Cultural Heritage", "“Ipak yoʻli” turizm va madaniy meros xalqaro universiteti", "Международный университет туризма и культурного наследия «Шёлковый путь»"],
  ["BukhSU", "buxdu.uz", "BUKHARA", "STATE", "Bukhara State University", "Buxoro davlat universiteti", "Бухарский государственный университет"],
  ["AndSU", "adu.uz", "ANDIJAN", "STATE", "Andijan State University", "Andijon davlat universiteti", "Андижанский государственный университет"],
  ["FerSU", "fdu.uz", "FERGANA", "STATE", "Fergana State University", "Fargʻona davlat universiteti", "Ферганский государственный университет"],
  ["NamSU", "namdu.uz", "NAMANGAN", "STATE", "Namangan State University", "Namangan davlat universiteti", "Наманганский государственный университет"],
  ["KarSU", "qarshidu.uz", "KASHKADARYA", "STATE", "Karshi State University", "Qarshi davlat universiteti", "Каршинский государственный университет"],
  ["UrSU", "urdu.uz", "KHOREZM", "STATE", "Urgench State University", "Urganch davlat universiteti", "Ургенчский государственный университет"],
  ["KSU", "karsu.uz", "KARAKALPAKSTAN", "STATE", "Karakalpak State University", "Qoraqalpoq davlat universiteti", "Каракалпакский государственный университет"],
  ["TerSU", "tersu.uz", "SURKHANDARYA", "STATE", "Termez State University", "Termiz davlat universiteti", "Термезский государственный университет"],
  ["GulSU", "guldu.uz", "SIRDARYA", "STATE", "Gulistan State University", "Guliston davlat universiteti", "Гулистанский государственный университет"],
  ["JizPI", "jizpi.uz", "JIZZAKH", "STATE", "Jizzakh Polytechnic Institute", "Jizzax politexnika instituti", "Джизакский политехнический институт"],
]
